services:
  llama-server:
    env_file:
      - .env
    image: ghcr.io/ggml-org/llama.cpp:server
    environment:
      LLAMA_API_KEY: ${LLAMA_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      - "./models:/models"
    command:
      - -m
      - /models/qwen2.5-0.5b-instruct-q4_k_m.gguf
      - --port
      - "8080"
      - --host
      - 0.0.0.0
      - -n
      - "512"
      - --api-key
      - ${LLAMA_API_KEY}
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command:
      - redis-server
      - --appendonly
      - "yes"
  server:
    env_file:
      - .env
    image: python:3.12-slim
    volumes:
      - ./src:/app
    working_dir: /app
    command:
      - sh
      - -c
      - pip install -r requirements.txt && python -u routers.py
    ports:
      - "8000:8000"
      - "9191:9191"
    restart: unless-stopped
    depends_on:
      - llama-server
      - redis
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: "1"
      LLAMA_API_URL: http://llama-server:8080/v1/chat/completions
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      CACHE_TTL_SECONDS: ${CACHE_TTL_SECONDS:-3600}

# No need for this, I have a separate prometheus instance running on my host machine
  # prometheus:
  #   image: prom/prometheus:latest
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #     - prometheus_data:/prometheus
  #   ports:
  #     - "9090:9090"

volumes:
  redis-data:
  # prometheus_data: